version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: node-sql
    volumes:
      - ./data:/docker-entrypoint-initdb.d